### ISSUE TITLE
add support for common-0.1.14 into nicholaswilde/gotify chart

### ISSUE THREAD

**Issue by alsarins** [nicholaswilde/helm-charts#125]
# Details

Please add common-0.1.14 into dependencies for nicholaswilde/gotify chart

### Description:
common-0.1.14 has fixes for envFrom. This way we can put gotify credentials in k8s secrets. 
common-0.1.13 lacks this ability.

Actions:
```
helm repo add nicholaswilde https://nicholaswilde.github.io/helm-charts/
helm repo update
```
and run
```
helm show all nicholaswilde/gotify
```
It shows dependency on version 0.1.13

```
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
```

Now I have to use workaround:
- manually pull chart and untar it locally, edit Chart.yaml and change dependencies to `version: ~0.1.14` 
- run `helm dependency update` 
- only after this steps I can upgrade existing installation: 

```
helm upgrade gotify . -n gotify -f ../gotify-values.yaml
```
