### ISSUE TITLE
[hedgedoc] s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize

### ISSUE THREAD

**Issue by dbluxo** [nicholaswilde/helm-charts#40]
Hi, I just updated the hedgedoc Helm Chart from `0.1.12` to `0.3.0` and I get the following error messages in a loop:

```
s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize: No such file or directory
s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize: No such file or directory
s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize: No such file or directory
s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize: No such file or directory
s6-applyuidgid: fatal: unable to exec ./node_modules/sequelize-cli/lib/sequelize: No such file or directory
```

I override the following Helm values in my installation:

```
env:
  TZ: "Europe/Berlin"
  CMD_URL_ADDPORT: "false"
  CMD_ALLOW_EMAIL_REGISTER: "false"
  CMD_LOGLEVEL: "info"
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hedgedoc-demo.xyz
  port:
    port: 3000
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: hedgedoc-demo.xyz
  enabled: true
  hosts:
    - host: "hedgedoc-demo.xyz"
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
persistence:
  config:
    enabled: true
    emptyDir: false
    mountPath: /config
    storageClass: "ebs-gp2"
    accessMode: ReadWriteOnce
    size: 8Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
```

Any ideas?
