### ISSUE TITLE
[novnc] ingress configuration

### ISSUE THREAD

**Issue by iptizer** [nicholaswilde/helm-charts#7]
# Details

**Helm chart name and version:**

* novnc 
  * chart=novnc-0.1.3 
  * app=1.2.0

**Container name and tag:**

* novnc:1.2.0-ls1

**What steps did you take and what happened:**

Implemented chart, minor mods, but more or less this: https://github.com/nicholaswilde/helm-charts/blob/main/charts/novnc/values.yaml#L31

**What did you expect to happen:**

Access through ingress should work.

**Problem description:**

* Adding the ingress config as mentioned in the chart does not work. I think the new spec for k9s 1.18 is used, but shouldn't this be used with a different apiVersion?
* https://github.com/nicholaswilde/helm-charts/blob/main/charts/novnc/values.yaml#L31

## Keeping as suggested throws the following error:

```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): unknown field "pathType" in io.k8s.api.networking.v1beta1.HTTPIngressPath
```

## Removing just the *pathType*, meaning the following, shows the following:

```
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  hosts:
    - host: "vnc.mydomain.de"
      paths:
        - path: /vnc.html
          #pathType: Prefix
```

![only_vnc html](https://user-images.githubusercontent.com/24313052/106767437-27193880-663b-11eb-8915-fb619f93fe80.png)

## When modifying ingress config as follows, it looks like it works, but does not connect

```
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  hosts:
    - host: "vnc.mydomain.de"
      paths:
        - path: /
          #pathType: Prefix
```

The novnc front page is displayed, but on click of connect, the following logs are thrown on the pod:

```
10.17.170.56 - - [03/Feb/2021 16:18:08] 10.17.170.56: Plain non-SSL (ws://) WebSocket connection
10.17.170.56 - - [03/Feb/2021 16:18:08] 10.17.170.56: Path: '/websockify'
10.17.170.56 - - [03/Feb/2021 16:18:08] connecting to: localhost:5900
10.17.170.56 - - [03/Feb/2021 16:18:08] Failed to connect to localhost:5900
```

Hints welcome :).
